import os
import json
from supabase import create_client, Client
from dotenv import load_dotenv
load_dotenv()

# ==========================================
# Note for Reviewers: DATA ORCHESTRATION PIPELINE (BRIDGE)
# This script acts as the crucial telemetry bridge between the upstream 
# anomaly detector (ADWIN/KSWIN) and the downstream xCARE DSS. 
# By enriching the raw statistical alert with the learner's actual interaction 
# history (exact answers, attempts, difficulty), it strictly grounds the Agentic RAG's 
# context window, thereby physically preventing generative hallucinations.
# ==========================================

# ==========================================
# 1. SUPABASE CLOUD CONFIGURATION
# Note for Reviewers: Keys securely fetched via Environment Variables to prevent credential leakage.
# ==========================================
SUPABASE_URL = os.environ.get("SUPABASE_URL", "your_supabase_url_here")
SUPABASE_KEY = os.environ.get("SUPABASE_KEY", "your_supabase_key_here")

try:
    supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)
except Exception as e:
    print(f"Database Initialization Error: {e}")

# ==========================================
# 2. TELEMETRY FUSION FUNCTION (ADWIN -> SUPABASE -> xCARE)
# ==========================================
def enrich_drift_alert_for_xcare(drift_json_path, output_path):
    """
    Reads the raw statistical drift alert, fetches the learner's recent 
    telemetry from Supabase, and compiles the comprehensive context payload 
    required by the xCARE adapter and Agentic RAG engine.
    """
    try:
        # 1. Read the raw alert generated by the upstream ADWIN/KSWIN detector
        with open(drift_json_path, 'r') as f:
            alert_data = json.load(f)
    except FileNotFoundError:
        print(f"❌ Error: The file {drift_json_path} could not be found.")
        return

    user_id = alert_data.get("xai_metadata", {}).get("affected_user_id")
    
    print(f"🚨 Intercepted Concept Drift alert for User ID: {user_id}")
    print("🔍 Fetching recent cognitive telemetry from Supabase for Agentic RAG grounding...")
    
    # 2. Query Supabase for this specific learner's historical context
    # We extract the critical variables needed by the XAI module to diagnose the pedagogical failure
    try:
        response = supabase.table("xGATES").select(
            "problem_id, correct, attempt_count, student_answer, item_difficulty, xlstm_prediction"
        ).eq("user_id", user_id).order("created_at", desc=True).limit(5).execute()
        
        # 3. Data Fusion
        # Append the "recent_student_interactions" block to the original JSON payload
        alert_data["recent_student_interactions"] = response.data
        
        # 4. Save the enriched JSON payload for the downstream pipeline
        with open(output_path, 'w', encoding='utf-8') as f:
            json.dump(alert_data, f, indent=4, ensure_ascii=False)
            
        print(f"✅ Success! Enriched payload '{output_path}' generated and ready for xCARE inference.")
        
    except Exception as e:
        print(f"❌ Database Query Error: {e}")

# ==========================================
# EXECUTION BLOCK
# ==========================================
if __name__ == "__main__":
    # Input file generated by the upstream anomaly detection module
    input_file = "drift_alert.json" 
    
    # Output file to be consumed by the downstream xCARE DSS module
    output_file = "xCARE_final_input.json" 
    
    enrich_drift_alert_for_xcare(input_file, output_file)