# =========================================================
# Note for Reviewers: EDUCATIONAL KNOWLEDGE BASE & GROUNDING
# This module serves as the foundational data layer for both the Learner Interface
# and the Agentic RAG engine. 
# 1. It structurally prevents LLM hallucinations by restricting the RAG's 
#    generative space strictly to these predefined, pedagogically validated items.
# 2. The 'item_difficulty' parameter is actively utilized by the downstream 
#    Continual-LoRA router to execute algorithmic Scaffolding (dynamic difficulty reduction).
# 3. The skill mapping aligns with the ASSISTments dataset structures.
# =========================================================

exercises_pool = {
    "Linear Equations": [
        # --- MULTIPLE CHOICE QUESTIONS (choose_1) ---
        {"problem_id": 3001, "assistment_id": 9001, "original": 1, "sequence_id": 501, "base_sequence_id": 500, "type": "choose_1", "question": "Find x: x + 5 = 12", "choices": ["5", "7", "10", "17"], "expected_answer": "7", "item_difficulty": 0.1, "hints": ["💡 Hint 1: You need to isolate x.", "💡 Hint 2: Subtract 5 from both sides (12 - 5)."]},
        {"problem_id": 3002, "assistment_id": 9002, "original": 1, "sequence_id": 501, "base_sequence_id": 500, "type": "choose_1", "question": "Find x: 3x = 18", "choices": ["3", "6", "9", "15"], "expected_answer": "6", "item_difficulty": 0.2, "hints": ["💡 Hint 1: x is multiplied by 3.", "💡 Hint 2: Divide both sides by 3 (18 / 3)."]},
        {"problem_id": 3003, "assistment_id": 9003, "original": 1, "sequence_id": 501, "base_sequence_id": 500, "type": "choose_1", "question": "Solve: x - 4 = -1", "choices": ["-5", "3", "5", "-3"], "expected_answer": "3", "item_difficulty": 0.3, "hints": ["💡 Hint 1: Cancel the -4 by adding.", "💡 Hint 2: Add 4 to both sides (-1 + 4)."]},
        {"problem_id": 3004, "assistment_id": 9004, "original": 1, "sequence_id": 501, "base_sequence_id": 500, "type": "choose_1", "question": "Solve: 2x + 2 = 10", "choices": ["4", "5", "8", "6"], "expected_answer": "4", "item_difficulty": 0.4, "hints": ["💡 Hint 1: Subtract the constant first.", "💡 Hint 2: 2x = 8, then divide by 2."]},
        {"problem_id": 3005, "assistment_id": 9005, "original": 1, "sequence_id": 501, "base_sequence_id": 500, "type": "choose_1", "question": "Find x: x/2 = 6", "choices": ["3", "4", "8", "12"], "expected_answer": "12", "item_difficulty": 0.3, "hints": ["💡 Hint 1: x is divided by 2.", "💡 Hint 2: Multiply both sides by 2."]},
        {"problem_id": 3006, "assistment_id": 9006, "original": 1, "sequence_id": 501, "base_sequence_id": 500, "type": "choose_1", "question": "Solve: -x = 7", "choices": ["7", "-7", "1/7", "0"], "expected_answer": "-7", "item_difficulty": 0.2, "hints": ["💡 Hint 1: Multiply or divide by -1.", "💡 Hint 2: The opposite of x is 7, so x is -7."]},
        {"problem_id": 3007, "assistment_id": 9007, "original": 1, "sequence_id": 501, "base_sequence_id": 500, "type": "choose_1", "question": "Find x: 5x - 5 = 20", "choices": ["5", "3", "4", "25"], "expected_answer": "5", "item_difficulty": 0.5, "hints": ["💡 Hint 1: Move the -5 to the other side.", "💡 Hint 2: 5x = 25, then divide by 5."]},
        {"problem_id": 3008, "assistment_id": 9008, "original": 1, "sequence_id": 501, "base_sequence_id": 500, "type": "choose_1", "question": "Solve: 10 = 2x", "choices": ["5", "20", "8", "12"], "expected_answer": "5", "item_difficulty": 0.2, "hints": ["💡 Hint 1: The variable is on the right, but the rule is the same.", "💡 Hint 2: Divide 10 by 2."]},
        {"problem_id": 3009, "assistment_id": 9009, "original": 1, "sequence_id": 501, "base_sequence_id": 500, "type": "choose_1", "question": "Find x: -2x + 1 = -7", "choices": ["4", "-4", "3", "-3"], "expected_answer": "4", "item_difficulty": 0.7, "hints": ["💡 Hint 1: Subtract 1 from both sides first.", "💡 Hint 2: -2x = -8. Divide by -2."]},
        {"problem_id": 3010, "assistment_id": 9010, "original": 1, "sequence_id": 501, "base_sequence_id": 500, "type": "choose_1", "question": "Solve: x/3 + 2 = 5", "choices": ["1", "3", "9", "6"], "expected_answer": "9", "item_difficulty": 0.6, "hints": ["💡 Hint 1: Subtract 2 from both sides.", "💡 Hint 2: x/3 = 3. Multiply by 3."]},
        
        # --- TEXT INPUT QUESTIONS (fill_in_1) ---
        {"problem_id": 3011, "assistment_id": 9011, "original": 1, "sequence_id": 501, "base_sequence_id": 500, "type": "fill_in_1", "question": "Solve: x + 10 = 25", "expected_answer": "15", "item_difficulty": 0.1, "hints": ["💡 Hint 1: Isolate x.", "💡 Hint 2: 25 - 10."]},
        {"problem_id": 3012, "assistment_id": 9012, "original": 1, "sequence_id": 501, "base_sequence_id": 500, "type": "fill_in_1", "question": "Solve: 4x = 24", "expected_answer": "6", "item_difficulty": 0.2, "hints": ["💡 Hint 1: Divide both sides.", "💡 Hint 2: 24 / 4."]},
        {"problem_id": 3013, "assistment_id": 9013, "original": 1, "sequence_id": 501, "base_sequence_id": 500, "type": "fill_in_1", "question": "Find x: x - 8 = 2", "expected_answer": "10", "item_difficulty": 0.2, "hints": ["💡 Hint 1: Cancel the subtraction.", "💡 Hint 2: 2 + 8."]},
        {"problem_id": 3014, "assistment_id": 9014, "original": 1, "sequence_id": 501, "base_sequence_id": 500, "type": "fill_in_1", "question": "Solve: 3x + 1 = 10", "expected_answer": "3", "item_difficulty": 0.4, "hints": ["💡 Hint 1: Subtract 1 first.", "💡 Hint 2: 3x = 9. Divide by 3."]},
        {"problem_id": 3015, "assistment_id": 9015, "original": 1, "sequence_id": 501, "base_sequence_id": 500, "type": "fill_in_1", "question": "Find x: x/4 = 5", "expected_answer": "20", "item_difficulty": 0.3, "hints": ["💡 Hint 1: Multiply to isolate x.", "💡 Hint 2: 5 * 4."]},
        {"problem_id": 3016, "assistment_id": 9016, "original": 1, "sequence_id": 501, "base_sequence_id": 500, "type": "fill_in_1", "question": "Solve: 10x - 10 = 90", "expected_answer": "10", "item_difficulty": 0.5, "hints": ["💡 Hint 1: Add 10 to both sides.", "💡 Hint 2: 10x = 100."]},
        {"problem_id": 3017, "assistment_id": 9017, "original": 1, "sequence_id": 501, "base_sequence_id": 500, "type": "fill_in_1", "question": "Find x: -x + 4 = 0", "expected_answer": "4", "item_difficulty": 0.4, "hints": ["💡 Hint 1: Move x to the other side.", "💡 Hint 2: x becomes positive."]},
        {"problem_id": 3018, "assistment_id": 9018, "original": 1, "sequence_id": 501, "base_sequence_id": 500, "type": "fill_in_1", "question": "Solve: 2.5x = 10", "expected_answer": "4", "item_difficulty": 0.6, "hints": ["💡 Hint 1: Decimals work the same way.", "💡 Hint 2: 10 / 2.5"]},
        {"problem_id": 3019, "assistment_id": 9019, "original": 1, "sequence_id": 501, "base_sequence_id": 500, "type": "fill_in_1", "question": "Solve: 7x + 2 = 16", "expected_answer": "2", "item_difficulty": 0.5, "hints": ["💡 Hint 1: Subtract 2.", "💡 Hint 2: 7x = 14."]},
        {"problem_id": 3020, "assistment_id": 9020, "original": 1, "sequence_id": 501, "base_sequence_id": 500, "type": "fill_in_1", "question": "Find x: 5(x - 1) = 20", "expected_answer": "5", "item_difficulty": 0.8, "hints": ["💡 Hint 1: Divide both sides by 5 first.", "💡 Hint 2: x - 1 = 4. Then add 1."]}
    ],

    "Algebra": [
        # --- MULTIPLE CHOICE QUESTIONS (choose_1) ---
        {"problem_id": 4001, "assistment_id": 9101, "original": 1, "sequence_id": 502, "base_sequence_id": 500, "type": "choose_1", "question": "Expand: 2(x + 4)", "choices": ["2x + 4", "2x + 8", "x + 8", "8x"], "expected_answer": "2x + 8", "item_difficulty": 0.2, "hints": ["💡 Hint 1: Distribute the 2.", "💡 Hint 2: Multiply 2 by x, and 2 by 4."]},
        {"problem_id": 4002, "assistment_id": 9102, "original": 1, "sequence_id": 502, "base_sequence_id": 500, "type": "choose_1", "question": "Simplify: 3x + 4x", "choices": ["7x", "12x", "x", "7x^2"], "expected_answer": "7x", "item_difficulty": 0.1, "hints": ["💡 Hint 1: Combine like terms.", "💡 Hint 2: 3 + 4 = 7."]},
        {"problem_id": 4003, "assistment_id": 9103, "original": 1, "sequence_id": 502, "base_sequence_id": 500, "type": "choose_1", "question": "Solve: 3x = x + 8", "choices": ["2", "4", "8", "6"], "expected_answer": "4", "item_difficulty": 0.5, "hints": ["💡 Hint 1: Group x on one side.", "💡 Hint 2: Subtract x from 3x to get 2x = 8."]},
        {"problem_id": 4004, "assistment_id": 9104, "original": 1, "sequence_id": 502, "base_sequence_id": 500, "type": "choose_1", "question": "Evaluate 2x^2 when x=3", "choices": ["12", "18", "36", "6"], "expected_answer": "18", "item_difficulty": 0.4, "hints": ["💡 Hint 1: Exponents first.", "💡 Hint 2: 3^2 = 9. Then 2 * 9."]},
        {"problem_id": 4005, "assistment_id": 9105, "original": 1, "sequence_id": 502, "base_sequence_id": 500, "type": "choose_1", "question": "Expand: -1(x - 5)", "choices": ["-x - 5", "x + 5", "-x + 5", "x - 5"], "expected_answer": "-x + 5", "item_difficulty": 0.4, "hints": ["💡 Hint 1: Distribute the negative sign.", "💡 Hint 2: Negative * Negative = Positive."]},
        {"problem_id": 4006, "assistment_id": 9106, "original": 1, "sequence_id": 502, "base_sequence_id": 500, "type": "choose_1", "question": "Factor: 5x + 10", "choices": ["5(x+2)", "10(x+1)", "5(x+10)", "x(5+10)"], "expected_answer": "5(x+2)", "item_difficulty": 0.5, "hints": ["💡 Hint 1: Find the common factor.", "💡 Hint 2: Both divide by 5."]},
        {"problem_id": 4007, "assistment_id": 9107, "original": 1, "sequence_id": 502, "base_sequence_id": 500, "type": "choose_1", "question": "Simplify: (x^3) * (x^4)", "choices": ["x^12", "x^7", "2x^7", "x"], "expected_answer": "x^7", "item_difficulty": 0.6, "hints": ["💡 Hint 1: When bases are the same, add exponents.", "💡 Hint 2: 3 + 4."]},
        {"problem_id": 4008, "assistment_id": 9108, "original": 1, "sequence_id": 502, "base_sequence_id": 500, "type": "choose_1", "question": "Solve: 5x - 2 = 2x + 7", "choices": ["3", "5", "9", "1"], "expected_answer": "3", "item_difficulty": 0.7, "hints": ["💡 Hint 1: Move all x to the left, numbers to the right.", "💡 Hint 2: 3x = 9."]},
        {"problem_id": 4009, "assistment_id": 9109, "original": 1, "sequence_id": 502, "base_sequence_id": 500, "type": "choose_1", "question": "Expand: (x+1)(x+2)", "choices": ["x^2+3x+2", "x^2+2", "2x+3", "x^2+2x+1"], "expected_answer": "x^2+3x+2", "item_difficulty": 0.7, "hints": ["💡 Hint 1: Use FOIL.", "💡 Hint 2: x^2 + 2x + 1x + 2."]},
        {"problem_id": 4010, "assistment_id": 9110, "original": 1, "sequence_id": 502, "base_sequence_id": 500, "type": "choose_1", "question": "If x=2, y=4, find 3x + y", "choices": ["10", "14", "24", "7"], "expected_answer": "10", "item_difficulty": 0.3, "hints": ["💡 Hint 1: Substitute the values.", "💡 Hint 2: 3(2) + 4."]},

        # --- TEXT INPUT QUESTIONS (fill_in_1) ---
        {"problem_id": 4011, "assistment_id": 9111, "original": 1, "sequence_id": 502, "base_sequence_id": 500, "type": "fill_in_1", "question": "Expand: 4(x - 2) (Format: ax-b)", "expected_answer": "4x-8", "item_difficulty": 0.2, "hints": ["💡 Hint 1: Distribute the 4.", "💡 Hint 2: 4*x and 4*-2."]},
        {"problem_id": 4012, "assistment_id": 9112, "original": 1, "sequence_id": 502, "base_sequence_id": 500, "type": "fill_in_1", "question": "Simplify: 10x - 3x", "expected_answer": "7x", "item_difficulty": 0.1, "hints": ["💡 Hint 1: Subtract the coefficients.", "💡 Hint 2: 10 - 3."]},
        {"problem_id": 4013, "assistment_id": 9113, "original": 1, "sequence_id": 502, "base_sequence_id": 500, "type": "fill_in_1", "question": "Solve: 4x = 2x + 10", "expected_answer": "5", "item_difficulty": 0.5, "hints": ["💡 Hint 1: Subtract 2x.", "💡 Hint 2: 2x = 10."]},
        {"problem_id": 4014, "assistment_id": 9114, "original": 1, "sequence_id": 502, "base_sequence_id": 500, "type": "fill_in_1", "question": "Evaluate x^3 when x=2", "expected_answer": "8", "item_difficulty": 0.3, "hints": ["💡 Hint 1: x times x times x.", "💡 Hint 2: 2 * 2 * 2."]},
        {"problem_id": 4015, "assistment_id": 9115, "original": 1, "sequence_id": 502, "base_sequence_id": 500, "type": "fill_in_1", "question": "Factor: 3x + 9 (Format: a(x+b))", "expected_answer": "3(x+3)", "item_difficulty": 0.4, "hints": ["💡 Hint 1: Extract the common factor 3.", "💡 Hint 2: 3 * x + 3 * 3."]},
        {"problem_id": 4016, "assistment_id": 9116, "original": 1, "sequence_id": 502, "base_sequence_id": 500, "type": "fill_in_1", "question": "Simplify: (x^6) / (x^2)", "expected_answer": "x^4", "item_difficulty": 0.6, "hints": ["💡 Hint 1: Subtract exponents for division.", "💡 Hint 2: 6 - 2."]},
        {"problem_id": 4017, "assistment_id": 9117, "original": 1, "sequence_id": 502, "base_sequence_id": 500, "type": "fill_in_1", "question": "Solve: 6x - 4 = 2x + 12", "expected_answer": "4", "item_difficulty": 0.8, "hints": ["💡 Hint 1: Group x on left, numbers on right.", "💡 Hint 2: 4x = 16."]},
        {"problem_id": 4018, "assistment_id": 9118, "original": 1, "sequence_id": 502, "base_sequence_id": 500, "type": "fill_in_1", "question": "Expand: (x-1)(x+1) (Format: x^2-a)", "expected_answer": "x^2-1", "item_difficulty": 0.7, "hints": ["💡 Hint 1: This is a difference of squares.", "💡 Hint 2: The middle terms cancel out."]},
        {"problem_id": 4019, "assistment_id": 9119, "original": 1, "sequence_id": 502, "base_sequence_id": 500, "type": "fill_in_1", "question": "Evaluate 5x - y if x=2, y=3", "expected_answer": "7", "item_difficulty": 0.3, "hints": ["💡 Hint 1: Replace variables.", "💡 Hint 2: 5(2) - 3."]},
        {"problem_id": 4020, "assistment_id": 9120, "original": 1, "sequence_id": 502, "base_sequence_id": 500, "type": "fill_in_1", "question": "Solve: -3(x-2) = -12", "expected_answer": "6", "item_difficulty": 0.8, "hints": ["💡 Hint 1: Divide by -3 first.", "💡 Hint 2: x - 2 = 4."]}
    ],

    "Mean;Table": [
        # --- MULTIPLE CHOICE QUESTIONS (choose_1) ---
        {"problem_id": 5001, "assistment_id": 9201, "original": 1, "sequence_id": 503, "base_sequence_id": 500, "type": "choose_1", "question": "Mean of 2, 4, 6?", "choices": ["4", "12", "2", "6"], "expected_answer": "4", "item_difficulty": 0.1, "hints": ["💡 Hint 1: Sum / Count.", "💡 Hint 2: 12 / 3."]},
        {"problem_id": 5002, "assistment_id": 9202, "original": 1, "sequence_id": 503, "base_sequence_id": 500, "type": "choose_1", "question": "Sum is 40, count is 8. Mean?", "choices": ["5", "32", "48", "320"], "expected_answer": "5", "item_difficulty": 0.2, "hints": ["💡 Hint 1: Mean = Sum / count.", "💡 Hint 2: 40 / 8."]},
        {"problem_id": 5003, "assistment_id": 9203, "original": 1, "sequence_id": 503, "base_sequence_id": 500, "type": "choose_1", "question": "Median of 1, 9, 5?", "choices": ["5", "1", "9", "15"], "expected_answer": "5", "item_difficulty": 0.3, "hints": ["💡 Hint 1: Sort them first.", "💡 Hint 2: 1, 5, 9. Middle is 5."]},
        {"problem_id": 5004, "assistment_id": 9204, "original": 1, "sequence_id": 503, "base_sequence_id": 500, "type": "choose_1", "question": "Mode of 3, 3, 4, 5?", "choices": ["3", "4", "5", "15"], "expected_answer": "3", "item_difficulty": 0.1, "hints": ["💡 Hint 1: Mode is the most frequent.", "💡 Hint 2: 3 appears twice."]},
        {"problem_id": 5005, "assistment_id": 9205, "original": 1, "sequence_id": 503, "base_sequence_id": 500, "type": "choose_1", "question": "Mean of 0, 10?", "choices": ["5", "10", "0", "2"], "expected_answer": "5", "item_difficulty": 0.2, "hints": ["💡 Hint 1: The 0 counts as a value.", "💡 Hint 2: 10 / 2."]},
        {"problem_id": 5006, "assistment_id": 9206, "original": 1, "sequence_id": 503, "base_sequence_id": 500, "type": "choose_1", "question": "Table: A(2), B(3). Total?", "choices": ["5", "2", "3", "6"], "expected_answer": "5", "item_difficulty": 0.1, "hints": ["💡 Hint 1: Add frequencies.", "💡 Hint 2: 2 + 3."]},
        {"problem_id": 5007, "assistment_id": 9207, "original": 1, "sequence_id": 503, "base_sequence_id": 500, "type": "choose_1", "question": "Mean of [10, x] is 15. x?", "choices": ["20", "5", "15", "30"], "expected_answer": "20", "item_difficulty": 0.6, "hints": ["💡 Hint 1: Total sum must be 15*2=30.", "💡 Hint 2: 30 - 10 = 20."]},
        {"problem_id": 5008, "assistment_id": 9208, "original": 1, "sequence_id": 503, "base_sequence_id": 500, "type": "choose_1", "question": "Mean of -2, 2?", "choices": ["0", "2", "-2", "4"], "expected_answer": "0", "item_difficulty": 0.3, "hints": ["💡 Hint 1: Sum is 0.", "💡 Hint 2: 0 / 2 = 0."]},
        {"problem_id": 5009, "assistment_id": 9209, "original": 1, "sequence_id": 503, "base_sequence_id": 500, "type": "choose_1", "question": "Which is affected by an outlier?", "choices": ["Mean", "Median", "Mode"], "expected_answer": "Mean", "item_difficulty": 0.5, "hints": ["💡 Hint 1: The one that uses all values to calculate.", "💡 Hint 2: Mean shifts towards extreme values."]},
        {"problem_id": 5010, "assistment_id": 9210, "original": 1, "sequence_id": 503, "base_sequence_id": 500, "type": "choose_1", "question": "Median of 2, 4, 6, 8?", "choices": ["5", "4", "6", "10"], "expected_answer": "5", "item_difficulty": 0.6, "hints": ["💡 Hint 1: Average the two middle numbers.", "💡 Hint 2: (4+6)/2."]},

        # --- TEXT INPUT QUESTIONS (fill_in_1) ---
        {"problem_id": 5011, "assistment_id": 9211, "original": 1, "sequence_id": 503, "base_sequence_id": 500, "type": "fill_in_1", "question": "Mean of 10, 20, 30?", "expected_answer": "20", "item_difficulty": 0.2, "hints": ["💡 Hint 1: Sum / 3.", "💡 Hint 2: 60 / 3."]},
        {"problem_id": 5012, "assistment_id": 9212, "original": 1, "sequence_id": 503, "base_sequence_id": 500, "type": "fill_in_1", "question": "Sum is 100, mean is 25. Count?", "expected_answer": "4", "item_difficulty": 0.4, "hints": ["💡 Hint 1: Count = Sum / Mean.", "💡 Hint 2: 100 / 25."]},
        {"problem_id": 5013, "assistment_id": 9213, "original": 1, "sequence_id": 503, "base_sequence_id": 500, "type": "fill_in_1", "question": "Median of 1, 2, 3, 4, 5?", "expected_answer": "3", "item_difficulty": 0.1, "hints": ["💡 Hint 1: Pick the middle.", "💡 Hint 2: 3."]},
        {"problem_id": 5014, "assistment_id": 9214, "original": 1, "sequence_id": 503, "base_sequence_id": 500, "type": "fill_in_1", "question": "Mode of 1, 1, 2, 3?", "expected_answer": "1", "item_difficulty": 0.1, "hints": ["💡 Hint 1: Most repeated.", "💡 Hint 2: 1."]},
        {"problem_id": 5015, "assistment_id": 9215, "original": 1, "sequence_id": 503, "base_sequence_id": 500, "type": "fill_in_1", "question": "Mean of 0, 0, 12?", "expected_answer": "4", "item_difficulty": 0.4, "hints": ["💡 Hint 1: Divide by 3.", "💡 Hint 2: 12 / 3."]},
        {"problem_id": 5016, "assistment_id": 9216, "original": 1, "sequence_id": 503, "base_sequence_id": 500, "type": "fill_in_1", "question": "Table frequencies: 5, 5, 5. Total?", "expected_answer": "15", "item_difficulty": 0.1, "hints": ["💡 Hint 1: Sum them.", "💡 Hint 2: 5*3."]},
        {"problem_id": 5017, "assistment_id": 9217, "original": 1, "sequence_id": 503, "base_sequence_id": 500, "type": "fill_in_1", "question": "Mean of [5, x] is 10. Find x.", "expected_answer": "15", "item_difficulty": 0.6, "hints": ["💡 Hint 1: Sum is 20.", "💡 Hint 2: 20 - 5."]},
        {"problem_id": 5018, "assistment_id": 9218, "original": 1, "sequence_id": 503, "base_sequence_id": 500, "type": "fill_in_1", "question": "Mean of -10, 10, 30?", "expected_answer": "10", "item_difficulty": 0.5, "hints": ["💡 Hint 1: Sum is 30.", "💡 Hint 2: 30 / 3."]},
        {"problem_id": 5019, "assistment_id": 9219, "original": 1, "sequence_id": 503, "base_sequence_id": 500, "type": "fill_in_1", "question": "Mean of 100, 100, 100?", "expected_answer": "100", "item_difficulty": 0.1, "hints": ["💡 Hint 1: All identical.", "💡 Hint 2: It's just 100."]},
        {"problem_id": 5020, "assistment_id": 9220, "original": 1, "sequence_id": 503, "base_sequence_id": 500, "type": "fill_in_1", "question": "Median of 10, 20, 30, 40?", "expected_answer": "25", "item_difficulty": 0.7, "hints": ["💡 Hint 1: Average of 20 and 30.", "💡 Hint 2: 50 / 2."]}
    ],

    "Probability Compound": [
        # --- MULTIPLE CHOICE QUESTIONS (choose_1) ---
        {"problem_id": 6001, "assistment_id": 9301, "original": 1, "sequence_id": 504, "base_sequence_id": 500, "type": "choose_1", "question": "P(Heads) on a coin?", "choices": ["1/2", "1/4", "1", "0"], "expected_answer": "1/2", "item_difficulty": 0.1, "hints": ["💡 Hint 1: 2 outcomes.", "💡 Hint 2: 1 out of 2."]},
        {"problem_id": 6002, "assistment_id": 9302, "original": 1, "sequence_id": 504, "base_sequence_id": 500, "type": "choose_1", "question": "P(Rolling 4) on a die?", "choices": ["1/6", "4/6", "1/4", "0"], "expected_answer": "1/6", "item_difficulty": 0.2, "hints": ["💡 Hint 1: 6 faces.", "💡 Hint 2: 1 out of 6."]},
        {"problem_id": 6003, "assistment_id": 9303, "original": 1, "sequence_id": 504, "base_sequence_id": 500, "type": "choose_1", "question": "P(Heads AND 4)?", "choices": ["1/12", "1/8", "1/2", "1/6"], "expected_answer": "1/12", "item_difficulty": 0.6, "hints": ["💡 Hint 1: Multiply them.", "💡 Hint 2: 1/2 * 1/6."]},
        {"problem_id": 6004, "assistment_id": 9304, "original": 1, "sequence_id": 504, "base_sequence_id": 500, "type": "choose_1", "question": "P(Red card) in a deck?", "choices": ["1/2", "1/4", "1/13", "1/52"], "expected_answer": "1/2", "item_difficulty": 0.3, "hints": ["💡 Hint 1: Half are red.", "💡 Hint 2: 26/52 = 1/2."]},
        {"problem_id": 6005, "assistment_id": 9305, "original": 1, "sequence_id": 504, "base_sequence_id": 500, "type": "choose_1", "question": "Flip 2 coins. P(Both Tails)?", "choices": ["1/4", "1/2", "1/8", "1"], "expected_answer": "1/4", "item_difficulty": 0.5, "hints": ["💡 Hint 1: 1/2 * 1/2.", "💡 Hint 2: 1/4."]},
        {"problem_id": 6006, "assistment_id": 9306, "original": 1, "sequence_id": 504, "base_sequence_id": 500, "type": "choose_1", "question": "P(Rolling 7) on a normal die?", "choices": ["0", "1/6", "1", "7/6"], "expected_answer": "0", "item_difficulty": 0.1, "hints": ["💡 Hint 1: Impossible event.", "💡 Hint 2: 0."]},
        {"problem_id": 6007, "assistment_id": 9307, "original": 1, "sequence_id": 504, "base_sequence_id": 500, "type": "choose_1", "question": "P(NOT rolling 1) on a die?", "choices": ["5/6", "1/6", "1/2", "0"], "expected_answer": "5/6", "item_difficulty": 0.4, "hints": ["💡 Hint 1: 1 - P(1).", "💡 Hint 2: 5 outcomes left out of 6."]},
        {"problem_id": 6008, "assistment_id": 9308, "original": 1, "sequence_id": 504, "base_sequence_id": 500, "type": "choose_1", "question": "P(Ace) in a deck?", "choices": ["1/13", "1/52", "4/13", "1/4"], "expected_answer": "1/13", "item_difficulty": 0.6, "hints": ["💡 Hint 1: 4 Aces in 52 cards.", "💡 Hint 2: 4/52 simplifies to 1/13."]},
        {"problem_id": 6009, "assistment_id": 9309, "original": 1, "sequence_id": 504, "base_sequence_id": 500, "type": "choose_1", "question": "P(A)=0.5, P(not A)=?", "choices": ["0.5", "1", "0", "1.5"], "expected_answer": "0.5", "item_difficulty": 0.2, "hints": ["💡 Hint 1: Must sum to 1.", "💡 Hint 2: 1 - 0.5."]},
        {"problem_id": 6010, "assistment_id": 9310, "original": 1, "sequence_id": 504, "base_sequence_id": 500, "type": "choose_1", "question": "Roll 2 dice. P(two 1s)?", "choices": ["1/36", "1/12", "1/6", "2/36"], "expected_answer": "1/36", "item_difficulty": 0.7, "hints": ["💡 Hint 1: 1/6 * 1/6.", "💡 Hint 2: 1/36."]},

        # --- TEXT INPUT QUESTIONS (fill_in_1) ---
        {"problem_id": 6011, "assistment_id": 9311, "original": 1, "sequence_id": 504, "base_sequence_id": 500, "type": "fill_in_1", "question": "P(Tails)? (Format: a/b)", "expected_answer": "1/2", "item_difficulty": 0.1, "hints": ["💡 Hint 1: Same as Heads.", "💡 Hint 2: 1/2."]},
        {"problem_id": 6012, "assistment_id": 9312, "original": 1, "sequence_id": 504, "base_sequence_id": 500, "type": "fill_in_1", "question": "P(Rolling 5)? (Format: a/b)", "expected_answer": "1/6", "item_difficulty": 0.2, "hints": ["💡 Hint 1: One face out of 6.", "💡 Hint 2: 1/6."]},
        {"problem_id": 6013, "assistment_id": 9313, "original": 1, "sequence_id": 504, "base_sequence_id": 500, "type": "fill_in_1", "question": "P(Tails AND 5)? (Format: a/b)", "expected_answer": "1/12", "item_difficulty": 0.6, "hints": ["💡 Hint 1: Multiply.", "💡 Hint 2: 1/2 * 1/6."]},
        {"problem_id": 6014, "assistment_id": 9314, "original": 1, "sequence_id": 504, "base_sequence_id": 500, "type": "fill_in_1", "question": "P(Black card)? (Format: a/b)", "expected_answer": "1/2", "item_difficulty": 0.3, "hints": ["💡 Hint 1: Half the deck.", "💡 Hint 2: 1/2."]},
        {"problem_id": 6015, "assistment_id": 9315, "original": 1, "sequence_id": 504, "base_sequence_id": 500, "type": "fill_in_1", "question": "Flip 2 coins. P(Both Heads)? (Format: a/b)", "expected_answer": "1/4", "item_difficulty": 0.5, "hints": ["💡 Hint 1: 1/2 * 1/2.", "💡 Hint 2: 1/4."]},
        {"problem_id": 6016, "assistment_id": 9316, "original": 1, "sequence_id": 504, "base_sequence_id": 500, "type": "fill_in_1", "question": "P(Rolling 8) on a normal die?", "expected_answer": "0", "item_difficulty": 0.1, "hints": ["💡 Hint 1: Does an 8 exist?", "💡 Hint 2: 0."]},
        {"problem_id": 6017, "assistment_id": 9317, "original": 1, "sequence_id": 504, "base_sequence_id": 500, "type": "fill_in_1", "question": "P(NOT rolling 2)? (Format: a/b)", "expected_answer": "5/6", "item_difficulty": 0.4, "hints": ["💡 Hint 1: 5 faces left.", "💡 Hint 2: 5/6."]},
        {"problem_id": 6018, "assistment_id": 9318, "original": 1, "sequence_id": 504, "base_sequence_id": 500, "type": "fill_in_1", "question": "P(King) in a deck? (Format: a/b)", "expected_answer": "1/13", "item_difficulty": 0.6, "hints": ["💡 Hint 1: 4 Kings in 52.", "💡 Hint 2: 1/13."]},
        {"problem_id": 6019, "assistment_id": 9319, "original": 1, "sequence_id": 504, "base_sequence_id": 500, "type": "fill_in_1", "question": "P(A)=0.2, P(not A)=?", "expected_answer": "0.8", "item_difficulty": 0.2, "hints": ["💡 Hint 1: 1 - 0.2.", "💡 Hint 2: 0.8."]},
        {"problem_id": 6020, "assistment_id": 9320, "original": 1, "sequence_id": 504, "base_sequence_id": 500, "type": "fill_in_1", "question": "Roll 2 dice. P(two 6s)? (Format: a/b)", "expected_answer": "1/36", "item_difficulty": 0.8, "hints": ["💡 Hint 1: 1/6 * 1/6.", "💡 Hint 2: 1/36."]}
    ],

    "Venn Diagram": [
        # --- MULTIPLE CHOICE QUESTIONS (choose_1) ---
        {"problem_id": 7001, "assistment_id": 9401, "original": 1, "sequence_id": 505, "base_sequence_id": 500, "type": "choose_1", "question": "Middle section?", "choices": ["Intersection", "Union", "Difference", "Complement"], "expected_answer": "Intersection", "item_difficulty": 0.2, "hints": ["💡 Hint 1: Where they overlap.", "💡 Hint 2: Intersection."]},
        {"problem_id": 7002, "assistment_id": 9402, "original": 1, "sequence_id": 505, "base_sequence_id": 500, "type": "choose_1", "question": "Symbol for Union?", "choices": ["∪", "∩", "∈", "⊂"], "expected_answer": "∪", "item_difficulty": 0.3, "hints": ["💡 Hint 1: Looks like a U.", "💡 Hint 2: ∪."]},
        {"problem_id": 7003, "assistment_id": 9403, "original": 1, "sequence_id": 505, "base_sequence_id": 500, "type": "choose_1", "question": "A={1,2}, B={2,3}. A ∩ B?", "choices": ["{2}", "{1,2,3}", "{1,3}", "{}"], "expected_answer": "{2}", "item_difficulty": 0.4, "hints": ["💡 Hint 1: What do they share?", "💡 Hint 2: {2}."]},
        {"problem_id": 7004, "assistment_id": 9404, "original": 1, "sequence_id": 505, "base_sequence_id": 500, "type": "choose_1", "question": "Outside the circles?", "choices": ["Complement", "Union", "Subset", "Intersection"], "expected_answer": "Complement", "item_difficulty": 0.4, "hints": ["💡 Hint 1: The opposite.", "💡 Hint 2: Complement."]},
        {"problem_id": 7005, "assistment_id": 9405, "original": 1, "sequence_id": 505, "base_sequence_id": 500, "type": "choose_1", "question": "No overlap means intersection is:", "choices": ["Empty Set", "Zero", "Infinite", "Subset"], "expected_answer": "Empty Set", "item_difficulty": 0.5, "hints": ["💡 Hint 1: Contains nothing.", "💡 Hint 2: Empty Set."]},
        {"problem_id": 7006, "assistment_id": 9406, "original": 1, "sequence_id": 505, "base_sequence_id": 500, "type": "choose_1", "question": "Word for Intersection?", "choices": ["AND", "OR", "NOT", "XOR"], "expected_answer": "AND", "item_difficulty": 0.3, "hints": ["💡 Hint 1: Both must be true.", "💡 Hint 2: AND."]},
        {"problem_id": 7007, "assistment_id": 9407, "original": 1, "sequence_id": 505, "base_sequence_id": 500, "type": "choose_1", "question": "Word for Union?", "choices": ["OR", "AND", "NOT", "NOR"], "expected_answer": "OR", "item_difficulty": 0.3, "hints": ["💡 Hint 1: One or the other.", "💡 Hint 2: OR."]},
        {"problem_id": 7008, "assistment_id": 9408, "original": 1, "sequence_id": 505, "base_sequence_id": 500, "type": "choose_1", "question": "A inside B means A is:", "choices": ["Subset", "Superset", "Union", "Complement"], "expected_answer": "Subset", "item_difficulty": 0.6, "hints": ["💡 Hint 1: Part of B.", "💡 Hint 2: Subset."]},
        {"problem_id": 7009, "assistment_id": 9409, "original": 1, "sequence_id": 505, "base_sequence_id": 500, "type": "choose_1", "question": "Total area of circles?", "choices": ["Union", "Intersection", "Complement", "Subset"], "expected_answer": "Union", "item_difficulty": 0.4, "hints": ["💡 Hint 1: Combined.", "💡 Hint 2: Union."]},
        {"problem_id": 7010, "assistment_id": 9410, "original": 1, "sequence_id": 505, "base_sequence_id": 500, "type": "choose_1", "question": "A={1}, B={2}. A ∪ B?", "choices": ["{1,2}", "{1}", "{2}", "{}"], "expected_answer": "{1,2}", "item_difficulty": 0.5, "hints": ["💡 Hint 1: Combine them.", "💡 Hint 2: {1,2}."]},

        # --- TEXT INPUT QUESTIONS (fill_in_1) ---
        {"problem_id": 7011, "assistment_id": 9411, "original": 1, "sequence_id": 505, "base_sequence_id": 500, "type": "fill_in_1", "question": "Set A={4,5}. Set B={5,6}. A ∩ B?", "expected_answer": "5", "item_difficulty": 0.2, "hints": ["💡 Hint 1: What is shared?", "💡 Hint 2: 5."]},
        {"problem_id": 7012, "assistment_id": 9412, "original": 1, "sequence_id": 505, "base_sequence_id": 500, "type": "fill_in_1", "question": "A has 10, B has 5. Share 2. Union size?", "expected_answer": "13", "item_difficulty": 0.6, "hints": ["💡 Hint 1: 10 + 5 - 2.", "💡 Hint 2: 13."]},
        {"problem_id": 7013, "assistment_id": 9413, "original": 1, "sequence_id": 505, "base_sequence_id": 500, "type": "fill_in_1", "question": "15 math, 10 art, 5 both. ONLY math?", "expected_answer": "10", "item_difficulty": 0.5, "hints": ["💡 Hint 1: Subtract both.", "💡 Hint 2: 15 - 5 = 10."]},
        {"problem_id": 7014, "assistment_id": 9414, "original": 1, "sequence_id": 505, "base_sequence_id": 500, "type": "fill_in_1", "question": "A={0}. B={0}. Union?", "expected_answer": "0", "item_difficulty": 0.2, "hints": ["💡 Hint 1: Combine.", "💡 Hint 2: 0."]},
        {"problem_id": 7015, "assistment_id": 9415, "original": 1, "sequence_id": 505, "base_sequence_id": 500, "type": "fill_in_1", "question": "Elements in {X, Y, Z}?", "expected_answer": "3", "item_difficulty": 0.1, "hints": ["💡 Hint 1: Count them.", "💡 Hint 2: 3."]},
        {"problem_id": 7016, "assistment_id": 9416, "original": 1, "sequence_id": 505, "base_sequence_id": 500, "type": "fill_in_1", "question": "Total=20. A∪B=15. Outside?", "expected_answer": "5", "item_difficulty": 0.4, "hints": ["💡 Hint 1: Total - Union.", "💡 Hint 2: 20 - 15 = 5."]},
        {"problem_id": 7017, "assistment_id": 9417, "original": 1, "sequence_id": 505, "base_sequence_id": 500, "type": "fill_in_1", "question": "A={1,3}, B={2,4}. Intersection size?", "expected_answer": "0", "item_difficulty": 0.3, "hints": ["💡 Hint 1: Nothing shared.", "💡 Hint 2: 0."]},
        {"problem_id": 7018, "assistment_id": 9418, "original": 1, "sequence_id": 505, "base_sequence_id": 500, "type": "fill_in_1", "question": "A∪B=12. A=8, B=6. Intersection?", "expected_answer": "2", "item_difficulty": 0.7, "hints": ["💡 Hint 1: 8 + 6 - 12.", "💡 Hint 2: 2."]},
        {"problem_id": 7019, "assistment_id": 9419, "original": 1, "sequence_id": 505, "base_sequence_id": 500, "type": "fill_in_1", "question": "10 play soccer, 5 play tennis, 0 both. Union?", "expected_answer": "15", "item_difficulty": 0.4, "hints": ["💡 Hint 1: Just add them.", "💡 Hint 2: 15."]},
        {"problem_id": 7020, "assistment_id": 9420, "original": 1, "sequence_id": 505, "base_sequence_id": 500, "type": "fill_in_1", "question": "A={9}, B={9}. Intersection?", "expected_answer": "9", "item_difficulty": 0.2, "hints": ["💡 Hint 1: They share it.", "💡 Hint 2: 9."]}
    ],

    "Scatter Plot": [
        # --- MULTIPLE CHOICE QUESTIONS (choose_1) ---
        {"problem_id": 8001, "assistment_id": 9501, "original": 1, "sequence_id": 506, "base_sequence_id": 500, "type": "choose_1", "question": "Upward points correlation?", "choices": ["Positive", "Negative", "None"], "expected_answer": "Positive", "item_difficulty": 0.2, "hints": ["💡 Hint 1: Goes up.", "💡 Hint 2: Positive."]},
        {"problem_id": 8002, "assistment_id": 9502, "original": 1, "sequence_id": 506, "base_sequence_id": 500, "type": "choose_1", "question": "Downward points correlation?", "choices": ["Negative", "Positive", "None"], "expected_answer": "Negative", "item_difficulty": 0.2, "hints": ["💡 Hint 1: Goes down.", "💡 Hint 2: Negative."]},
        {"problem_id": 8003, "assistment_id": 9503, "original": 1, "sequence_id": 506, "base_sequence_id": 500, "type": "choose_1", "question": "Random points correlation?", "choices": ["None", "Positive", "Negative"], "expected_answer": "None", "item_difficulty": 0.2, "hints": ["💡 Hint 1: No pattern.", "💡 Hint 2: None."]},
        {"problem_id": 8004, "assistment_id": 9504, "original": 1, "sequence_id": 506, "base_sequence_id": 500, "type": "choose_1", "question": "Line through center?", "choices": ["Line of best fit", "Equator", "Outlier", "Axis"], "expected_answer": "Line of best fit", "item_difficulty": 0.4, "hints": ["💡 Hint 1: Best fits data.", "💡 Hint 2: Line of best fit."]},
        {"problem_id": 8005, "assistment_id": 9505, "original": 1, "sequence_id": 506, "base_sequence_id": 500, "type": "choose_1", "question": "Point far away?", "choices": ["Outlier", "Inlier", "Average", "Slope"], "expected_answer": "Outlier", "item_difficulty": 0.4, "hints": ["💡 Hint 1: Outside pattern.", "💡 Hint 2: Outlier."]},
        {"problem_id": 8006, "assistment_id": 9506, "original": 1, "sequence_id": 506, "base_sequence_id": 500, "type": "choose_1", "question": "Study hours vs Test Score?", "choices": ["Positive", "Negative", "None"], "expected_answer": "Positive", "item_difficulty": 0.3, "hints": ["💡 Hint 1: Both go up.", "💡 Hint 2: Positive."]},
        {"problem_id": 8007, "assistment_id": 9507, "original": 1, "sequence_id": 506, "base_sequence_id": 500, "type": "choose_1", "question": "Car weight vs mpg?", "choices": ["Negative", "Positive", "None"], "expected_answer": "Negative", "item_difficulty": 0.5, "hints": ["💡 Hint 1: One up, one down.", "💡 Hint 2: Negative."]},
        {"problem_id": 8008, "assistment_id": 9508, "original": 1, "sequence_id": 506, "base_sequence_id": 500, "type": "choose_1", "question": "Shoe size vs Math score?", "choices": ["None", "Positive", "Negative"], "expected_answer": "None", "item_difficulty": 0.2, "hints": ["💡 Hint 1: No link.", "💡 Hint 2: None."]},
        {"problem_id": 8009, "assistment_id": 9509, "original": 1, "sequence_id": 506, "base_sequence_id": 500, "type": "choose_1", "question": "Predicting outside graph?", "choices": ["Extrapolation", "Interpolation", "Correlation"], "expected_answer": "Extrapolation", "item_difficulty": 0.7, "hints": ["💡 Hint 1: Extra.", "💡 Hint 2: Extrapolation."]},
        {"problem_id": 8010, "assistment_id": 9510, "original": 1, "sequence_id": 506, "base_sequence_id": 500, "type": "choose_1", "question": "Predicting inside graph?", "choices": ["Interpolation", "Extrapolation", "Causation"], "expected_answer": "Interpolation", "item_difficulty": 0.7, "hints": ["💡 Hint 1: Inter.", "💡 Hint 2: Interpolation."]},

        # --- TEXT INPUT QUESTIONS (fill_in_1) ---
        {"problem_id": 8011, "assistment_id": 9511, "original": 1, "sequence_id": 506, "base_sequence_id": 500, "type": "fill_in_1", "question": "r=1 means what correlation? (Word)", "expected_answer": "Positive", "item_difficulty": 0.6, "hints": ["💡 Hint 1: Greater than 0.", "💡 Hint 2: Positive."]},
        {"problem_id": 8012, "assistment_id": 9512, "original": 1, "sequence_id": 506, "base_sequence_id": 500, "type": "fill_in_1", "question": "r=-1 means what correlation? (Word)", "expected_answer": "Negative", "item_difficulty": 0.6, "hints": ["💡 Hint 1: Less than 0.", "💡 Hint 2: Negative."]},
        {"problem_id": 8013, "assistment_id": 9513, "original": 1, "sequence_id": 506, "base_sequence_id": 500, "type": "fill_in_1", "question": "r=0 means what correlation? (Word)", "expected_answer": "None", "item_difficulty": 0.5, "hints": ["💡 Hint 1: Zero link.", "💡 Hint 2: None."]},
        {"problem_id": 8014, "assistment_id": 9514, "original": 1, "sequence_id": 506, "base_sequence_id": 500, "type": "fill_in_1", "question": "y = 2x. If x=5, y=?", "expected_answer": "10", "item_difficulty": 0.3, "hints": ["💡 Hint 1: Multiply.", "💡 Hint 2: 10."]},
        {"problem_id": 8015, "assistment_id": 9515, "original": 1, "sequence_id": 506, "base_sequence_id": 500, "type": "fill_in_1", "question": "y = -x. If x=4, y=?", "expected_answer": "-4", "item_difficulty": 0.3, "hints": ["💡 Hint 1: Add minus.", "💡 Hint 2: -4."]},
        {"problem_id": 8016, "assistment_id": 9516, "original": 1, "sequence_id": 506, "base_sequence_id": 500, "type": "fill_in_1", "question": "Horizontal axis letter?", "expected_answer": "x", "item_difficulty": 0.1, "hints": ["💡 Hint 1: Left to right.", "💡 Hint 2: x."]},
        {"problem_id": 8017, "assistment_id": 9517, "original": 1, "sequence_id": 506, "base_sequence_id": 500, "type": "fill_in_1", "question": "Vertical axis letter?", "expected_answer": "y", "item_difficulty": 0.1, "hints": ["💡 Hint 1: Up and down.", "💡 Hint 2: y."]},
        {"problem_id": 8018, "assistment_id": 9518, "original": 1, "sequence_id": 506, "base_sequence_id": 500, "type": "fill_in_1", "question": "Slope of y = 3x + 1?", "expected_answer": "3", "item_difficulty": 0.4, "hints": ["💡 Hint 1: Number before x.", "💡 Hint 2: 3."]},
        {"problem_id": 8019, "assistment_id": 9519, "original": 1, "sequence_id": 506, "base_sequence_id": 500, "type": "fill_in_1", "question": "Intercept of y = x + 5?", "expected_answer": "5", "item_difficulty": 0.4, "hints": ["💡 Hint 1: Number alone.", "💡 Hint 2: 5."]},
        {"problem_id": 8020, "assistment_id": 9520, "original": 1, "sequence_id": 506, "base_sequence_id": 500, "type": "fill_in_1", "question": "If slope is 0, what is the 'r' value?", "expected_answer": "0", "item_difficulty": 0.8, "hints": ["💡 Hint 1: Flat line.", "💡 Hint 2: 0."]}
    ]
}

# --- UI & TELEMETRY METADATA ---
skill_mapping = { 
    "Linear Equations": 101, 
    "Algebra": 102, 
    "Mean;Table": 103, 
    "Probability Compound": 104, 
    "Venn Diagram": 105, 
    "Scatter Plot": 106 
}

subject_meta = {
    "Linear Equations": {"color": "#b2f5ea", "icon": "📏", "desc": "Find x, variables, balancing.", "assignment_id": 1001, "problem_set_type": "Linear"},
    "Algebra":          {"color": "#e1bee7", "icon": "🧮", "desc": "Expand, factorize, solve.", "assignment_id": 1002, "problem_set_type": "Linear"},
    "Mean;Table":       {"color": "#ffecb3", "icon": "📊", "desc": "Averages, tables, freq.", "assignment_id": 1003, "problem_set_type": "Linear"},
    "Probability Compound": {"color": "#c8e6c9", "icon": "🎲", "desc": "Coin tosses, dice rolls.", "assignment_id": 1004, "problem_set_type": "Linear"},
    "Venn Diagram":     {"color": "#f8bbd0", "icon": "⭕", "desc": "Intersections, unions.", "assignment_id": 1005, "problem_set_type": "Linear"},
    "Scatter Plot":     {"color": "#bbdefb", "icon": "📈", "desc": "Correlations, trends.", "assignment_id": 1006, "problem_set_type": "Linear"}
}